### PR TITLE
Improvement/speed

### PR DESCRIPTION
**Pull request by LarsHuebner-LHNW**
### Improved the speed of czt and iczt.

- czt is now a factor ~2 faster by avoiding multiple calculations of terms like W ** (k ** 2 / 2).
- Did the same for iczt and also got rid of slow python loops by changing
```python3
    p = np.empty(n, dtype=complex)
    p[0] = 1
    p[1:] = W ** k[1:] - 1
    for ki in range(1, n):
        p[ki] *= p[ki - 1]
    u = (-1) ** k * W ** ((2 * k ** 2 - (2 * n - 1) * k + n * (n - 1)) / 2) / p
    for ki in range(n):
        u[ki] /= p[n - ki - 1]
```
to
```python3
    p = np.r_[1, (W ** k[1:] - 1).cumprod()]
    u = (-1) ** k * W ** (k * (k - n + 0.5) + (n / 2 - 0.5) * n) / p
    u /= p[::-1]
```
to improve speed by about 2 orders of magnitdue there.

- Instead of if/elif-switches now using dictionary lookup for toeplitz multiplication and unified their internal calls.
- iczt with simple=False now also respects t_method. However, due to floating point arithmetic the methods have different numerical accuracy for large M=N, |A| != 1 and if W = np.exp(arg) with arg a non-integer multiple of 2j * np.pi / M. This is expected due to double precision complex numbers (Compare with Sukhoy & Stoytchev 2019).

**Note:** instead of u/=p[::-1] I also tested to create u directly with .../(p*p[::-1]), but this did not change the performance. However it did influence the accuracy of the result, but I currently don't know if that change made it better or worse. Therefore I reverted that line of code to keep the accuracy unchanged compared to the main branch when using t_method="ce". 

### Other changes unrelated to performance

- Accidentally ran the code formatter of my IDE out of habit. If you are unhappy with this i can revert this. 
- I changed things like "print(message)+raise Error" to "raise Error(message)"

### CODE REVIEW

**Comment by garrettj403** [comment]
Hi @LarsHuebner-LHNW, that looks great! Thank you for your contribution.

> Instead of if/elif-switches now using dictionary lookup for toeplitz multiplication and unified their internal calls.

I like that. Much cleaner.

> Note: instead of u/=p[::-1] I also tested to create u directly with .../(p*p[::-1]), but this did not change the performance. However it did influence the accuracy of the result, but I currently don't know if that change made it better or worse. Therefore I reverted that line of code to keep the accuracy unchanged compared to the main branch when using t_method="ce".

That's interesting. I'll have to devise some better tests, although, it shouldn't be an issue for most applications.

> Accidentally ran the code formatter of my IDE out of habit. If you are unhappy with this i can revert this.

That's fine but there are a couple lines I might change back (e.g., line 126-131).

**Comment by garrettj403** [comment]
@LarsHuebner-LHNW, a couple of the tests aren't working now...

For example, in `test_compare_czt_fft_dft`, the CZT algorithm should produce the exact same result as the FFT. It works if I change `decimal=10` but it seems like this is a step in the wrong direction.

I'll need to look at this later on.

**Comment by LarsHuebner-LHNW** [comment]
@garrettj403 : Sorry, I did some tests in a jupyter notebook. Probably I some things there and my commit needs some fine-tuning. Will look again into this

**Comment by LarsHuebner-LHNW** [comment]
@garrettj403 I updated my branch and fixed the inaccurcy issue. Now tests run fine with decimal you specified. I only checked with np.allclose before. Will open a new pull request with the changes.

**Pull request merged**
